spring.application.name=airports 
# Define cores no terminal 
spring.output.ansi.enabled=always 
# Define path raiz do endpoint 
# http://localhost:8080/garagem99/algumacoisa 
server.servlet.context-path=/garagem99 